### ISSUE TITLE
< and > symbol rendering

### ISSUE THREAD

**Issue by thistleBgood** [FelixMcFelix/laughing-ironman#1]
Unless included in a {lstlisting}, the symbols < and > aren't rendered properly in the final pdf. They should be replaced by \textless and \textgreater respectively. Noticed in section 1.4 with the <canvas> html tag.

**Comment by FelixMcFelix** [comment]
Handled as of d29b0314e873d91d108fba2f5354e21e5168d0a7. Leaving open in case others need this.

**Comment by FelixMcFelix** [comment]
Dissertation stage is long passed, closing issue.
